var hierarchy =
[
    [ "std::array< T >", null, [
      [ "Dune::IGA::Utilities::Domain< double >", "da/d73/a01090.html", null ],
      [ "Dune::IGA::Utilities::Domain< ScalarType >", "da/d73/a01090.html", null ]
    ] ],
    [ "BoundaryPatchEnclosingVerticesPropertyTrimmed< GridView, ncomp >", "dd/d40/a01762.html", null ],
    [ "Dune::IGA::Splines::BsplineBasis< ScalarType_ >", "d5/d10/a01738.html", null ],
    [ "Dune::Capabilities::canCommunicate< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "d3/ddc/a01142.html", null ],
    [ "Dune::Capabilities::canCommunicate< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d0/d39/a01138.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Util::ClippingResult", "d4/d99/a01634.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridFamily< dim, dimworld, ScalarType >::ParameterSpaceTraits::Codim< codim >", "d0/d34/a01486.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedReferenceElement< dim, GridImp >::Codim< codim >", "d5/dcf/a01602.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridFamily< dim, dimworld, ScalarType >::ParameterSpaceTraits::Codim< codim >", "d4/d8e/a01694.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedReferenceElement< dim, GridImp >::Codim< 0 >", "d5/dcf/a01602.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< dim_, dimworld_, ScalarType >::ConnectionResult", "da/d4e/a01106.html", null ],
    [ "Dune::IGA::ControlPoint< VT >", "d9/df5/a01086.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchTrimDataImpl< GridImp >::CurveManager", "dc/def/a01594.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::DefaultIntegrationRuleGenerator< GridImp >", "d0/d00/a01286.html", null ],
    [ "DefaultLeafGridView", null, [
      [ "Dune::IGA::PatchGridLeafGridView< GridImp >", "de/d33/a01274.html", null ]
    ] ],
    [ "DefaultLeafGridViewTraits", null, [
      [ "Dune::IGA::PatchGridLeafGridViewTraits< GridImp >", "d8/d17/a01282.html", null ]
    ] ],
    [ "DefaultLevelGridView", null, [
      [ "Dune::IGA::PatchGridLevelGridView< GridImp >", "da/d00/a01270.html", null ]
    ] ],
    [ "DefaultLevelGridViewTraits", null, [
      [ "Dune::IGA::PatchGridLevelGridViewTraits< GridImp >", "d4/d10/a01278.html", null ]
    ] ],
    [ "Dune::DGFGridFactory< IGA::PatchGrid< dim, dimworld, GridFamily_, ScalarType > >", "db/d4b/a01786.html", null ],
    [ "Dune::DGFGridInfo< IGA::PatchGrid< dim, dimworld, GridFamily_, ScalarType > >", "d2/d20/a01790.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, ScalarType >::DummyEmpty", "dc/d25/a01406.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::ElementTrimDataImpl< Grid >::EdgeInfo", "dc/de6/a01426.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::ElementTrimDataContainerImpl< ParameterSpaceGrid >", "d6/d26/a01678.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::ElementTrimDataImpl< Grid >", "d4/d3c/a01418.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::ElementTrimDataImpl< mydim_, ScalarType >", "dc/d42/a01674.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::ElementTrimDataImpl< GridImp >", "d4/d3c/a01418.html", null ],
    [ "Dune::EnableBoundarySegmentIndexCheck< Grid >", "d9/d2e/a01194.html", null ],
    [ "EnableLevelIntersectionIteratorCheck< Grid >", "d0/d32/a01198.html", null ],
    [ "EnableLevelIntersectionIteratorCheck< Dune::IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "dc/d9e/a01206.html", null ],
    [ "EntityDefaultImplementation", null, [
      [ "Dune::IGA::PatchGridEntity< codim, dim, GridImp >", "d0/d58/a01230.html", null ],
      [ "Dune::IGA::PatchGridEntity< 0, dim, GridImp >", "d8/ddf/a01238.html", null ]
    ] ],
    [ "Dune::IGA::DefaultParameterSpace::EntityInfoImpl< Traits, codim >", "d0/de2/a01442.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::EntityInfoImpl< Traits, 0 >", "d7/dd1/a01458.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::EntityInfoImpl< Traits, 1 >", "d3/da3/a01450.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::EntityInfoImpl< Traits, 2 >", "d8/d22/a01446.html", null ],
    [ "Dune::Std::expected< T, E >", "d9/de3/a01758.html", null ],
    [ "std::false_type", null, [
      [ "Dune::EnableBoundarySegmentIndexCheck< Dune::IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d4/d5d/a01202.html", null ],
      [ "is_instantiation_of< Template, T >", "df/d21/a01778.html", null ]
    ] ],
    [ "Dune::IGA::DefaultParameterSpace::Util::FindIntersectionResult", "d9/d79/a01658.html", null ],
    [ "GeometryDefaultImplementation", null, [
      [ "Dune::IGA::PatchGridGeometry< mydim, coorddim, GridImp >", "dc/d83/a01254.html", null ],
      [ "Dune::IGA::PatchGridLocalGeometry< mydim, coorddim, GridImp >", "de/db5/a01730.html", null ]
    ] ],
    [ "Dune::IGA::DefaultParameterSpace::EntityInfoImpl< Traits, 1 >::GeometryMap", "da/df6/a01454.html", null ],
    [ "GridDefaultImplementation", null, [
      [ "Dune::IGA::PatchGrid< dim, dimworld, GridFamily_, ScalarType >", "dd/d9e/a01226.html", null ]
    ] ],
    [ "Dune::GridFactory< IGA::PatchGrid< dim_, dimworld_, ParameterSpaceType_, ScalarType > >", "d7/dc5/a01242.html", null ],
    [ "Dune::Capabilities::hasBackupRestoreFacilities< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "dc/dee/a01166.html", null ],
    [ "Dune::Capabilities::hasBackupRestoreFacilities< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d4/d13/a01162.html", null ],
    [ "Dune::Capabilities::hasEntity< const Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "db/d1e/a01126.html", null ],
    [ "Dune::Capabilities::hasEntity< const IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "dd/d09/a01118.html", null ],
    [ "Dune::Capabilities::hasEntity< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "db/d32/a01122.html", null ],
    [ "Dune::Capabilities::hasEntityIterator< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "dd/de2/a01134.html", null ],
    [ "Dune::Capabilities::hasEntityIterator< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d0/d61/a01130.html", null ],
    [ "std::hash< Dune::IGA::DefaultParameterSpace::IdType< HostIdType > >", "d5/d67/a01466.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::HostGridAccess< Grid >", "d7/def/a01538.html", null ],
    [ "Dune::IGA::HostGridAccess< Grid >", "de/d7e/a01222.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Util::ClippingResult::Vertex::HostVertexImpl", "d7/d94/a01642.html", null ],
    [ "Dune::IGA::Ibra::IbraBase", "d6/dfa/a01318.html", [
      [ "Dune::IGA::Ibra::IbraNURBSData< 1, 2 >", "d5/df4/a01322.html", null ],
      [ "Dune::IGA::Ibra::Brep< worldDim >", "d9/de4/a01346.html", null ],
      [ "Dune::IGA::Ibra::BrepLoop", "d2/d4d/a01338.html", null ],
      [ "Dune::IGA::Ibra::BrepLoopRepresentation", "d4/dd1/a01334.html", null ],
      [ "Dune::IGA::Ibra::BrepRepresentation", "d5/da0/a01342.html", null ],
      [ "Dune::IGA::Ibra::BrepTrim", "d5/d78/a01330.html", null ],
      [ "Dune::IGA::Ibra::BrepTrimRepresentation", "d1/d54/a01326.html", null ],
      [ "Dune::IGA::Ibra::IbraNURBSData< dim, worldDim >", "d5/df4/a01322.html", null ]
    ] ],
    [ "Dune::IGA::IbraReader< dim, dimworld, PatchGrid, HasCurve >", "de/d5c/a01358.html", null ],
    [ "Dune::IGA::IbraReader< dim, dimworld, PatchGrid, false >", "d6/dfe/a01366.html", null ],
    [ "Dune::IGA::IbraReader< dim, dimworld, PatchGrid, true >", "da/dab/a01362.html", null ],
    [ "IdSet", null, [
      [ "Dune::IGA::DefaultParameterSpace::PatchGridGlobalIdSet< GridImp >", "de/d36/a01462.html", null ],
      [ "Dune::IGA::DefaultParameterSpace::PatchGridLocalIdSet< GridImp >", "d7/d22/a01514.html", null ],
      [ "Dune::IGA::IdentityParameterSpace::PatchGridGlobalIdSet< GridImp >", "d9/dbc/a01662.html", null ],
      [ "Dune::IGA::IdentityParameterSpace::PatchGridLocalIdSet< GridImp >", "d8/d75/a01666.html", null ]
    ] ],
    [ "Dune::IGA::DefaultParameterSpace::IdType< HostIdType >", "d5/dd0/a01438.html", null ],
    [ "Dune::IGA::IGARefinedGeometries< GridView >", "d2/dff/a01374.html", null ],
    [ "IndexSet", null, [
      [ "Dune::IGA::DefaultParameterSpace::PatchGridLeafIndexSet< GridImp >", "dc/d47/a01510.html", null ],
      [ "Dune::IGA::DefaultParameterSpace::PatchGridLevelIndexSet< GridImp >", "db/d57/a01506.html", null ],
      [ "Dune::IGA::IdentityParameterSpace::PatchGridLeafIndexSet< GridImp >", "d6/d9a/a01710.html", null ],
      [ "Dune::IGA::IdentityParameterSpace::PatchGridLevelIndexSet< GridImp >", "db/dbe/a01706.html", null ]
    ] ],
    [ "Dune::IGA::DefaultParameterSpace::Util::ClippingResult::Vertex::InsideVertexImpl", "d9/d3b/a01650.html", null ],
    [ "Dune::IGA::IntegrationRuleHolder< GridImp >", "dc/ded/a01290.html", null ],
    [ "Dune::IGA::IntegrationRuleHolder< Dune::IGA::PatchGrid >", "dc/ded/a01290.html", null ],
    [ "Dune::Capabilities::isCartesian< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "dc/d19/a01190.html", null ],
    [ "Dune::Capabilities::isCartesian< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d9/dbb/a01186.html", null ],
    [ "Dune::Capabilities::isLeafwiseConforming< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "df/db5/a01158.html", null ],
    [ "Dune::Capabilities::isLeafwiseConforming< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d5/d16/a01154.html", null ],
    [ "Dune::Capabilities::isLevelwiseConforming< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d2/d7b/a01150.html", null ],
    [ "Dune::Capabilities::isLevelwiseConforming< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "de/d07/a01146.html", null ],
    [ "Dune::IteratorRange", null, [
      [ "Dune::IGA::DefaultParameterSpace::TrimmedReferenceElement< dim, GridImp >::SubEntityRangeImpl", "d3/d2d/a01606.html", null ]
    ] ],
    [ "LeafBasisNode", null, [
      [ "Dune::Functions::NurbsNode< GV >", "da/de3/a01398.html", null ]
    ] ],
    [ "Dune::IGA::Trim::LocalGeometryVariant< ParameterSpaceType_, Implementations >", "d0/d1f/a01734.html", null ],
    [ "Dune::IGA::Splines::Nurbs< dim, ScalarType_ >::LocalView", "d5/dfa/a01746.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::LoopHandler< ParameterSpace >", "d9/dfd/a01610.html", null ],
    [ "Dune::IGA::MultiDimensionalNet< netdim, ElementType, Container >", "d4/dfe/a01770.html", null ],
    [ "Dune::IGA::MultiDimensionalNet< dim, ControlPointType >", "d4/dfe/a01770.html", null ],
    [ "Dune::IGA::MultiDimensionalNet< dim, ScalarType >", "d4/dfe/a01770.html", null ],
    [ "Dune::IGA::MultiDimensionalNetIndex< netdim >", "d9/d02/a01774.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Util::ClippingResult::Vertex::NewVertexImpl", "df/dee/a01646.html", null ],
    [ "mapbox::util::nth< 0, Dune::FieldVector< T, 2 > >", "dc/de0/a01302.html", null ],
    [ "mapbox::util::nth< 1, Dune::FieldVector< T, 2 > >", "d7/d8c/a01306.html", null ],
    [ "Dune::IGA::Splines::Nurbs< dim, ScalarType_ >", "d1/dd5/a01742.html", null ],
    [ "Dune::IGA::Splines::Nurbs< mydimension, ctype >", "d1/dd5/a01742.html", null ],
    [ "Dune::IGA::Splines::Nurbs< mydimension, double >", "d1/dd5/a01742.html", null ],
    [ "Dune::Functions::NurbsLocalBasis< GV, R >", "d3/deb/a01386.html", null ],
    [ "Dune::Functions::NurbsLocalBasis< GV, double >", "d3/deb/a01386.html", null ],
    [ "Dune::Functions::NurbsLocalCoefficients< dim >", "d5/d8e/a01390.html", null ],
    [ "Dune::Functions::NurbsLocalFiniteElement< GV, R >", "de/d9d/a01382.html", null ],
    [ "Dune::Functions::NurbsLocalFiniteElement< GV, double >", "de/d9d/a01382.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, LB >", "d6/d2f/a01394.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, Dune::Functions::NurbsLocalBasis< GV, double > >", "d6/d2f/a01394.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, Dune::Functions::NurbsLocalBasis< GV, R > >", "d6/d2f/a01394.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< dim_, dimworld_, ScalarType >", "d4/da7/a01102.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< dim, dimworld, ctype >", "d4/da7/a01102.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< GridImp::dimension, worlddimension, ctype >", "d4/da7/a01102.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< mydimension, coorddimension, ctype >", "d4/da7/a01102.html", null ],
    [ "Dune::IGA::NURBSPatchData< dim, dimworld_, ScalarType >", "dc/d3a/a01750.html", null ],
    [ "Dune::IGA::NURBSPatchData< dim, dimworld >", "dc/d3a/a01750.html", null ],
    [ "Dune::IGA::NURBSPatchData< dim, dimworld, ctype >", "dc/d3a/a01750.html", null ],
    [ "Dune::IGA::NURBSPatchData< mydimension, worlddimension, ctype >", "dc/d3a/a01750.html", null ],
    [ "Dune::IGA::NURBSPatchData< mydimension, worlddimension, double >", "dc/d3a/a01750.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, ScalarType >", "d2/da6/a01210.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV >", "d2/da6/a01210.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, double >", "d2/da6/a01210.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, R >", "d2/da6/a01210.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Parameter", "d0/da4/a01470.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::Parameter", "de/df6/a01670.html", null ],
    [ "Dune::IGA::SimplexGenerator< GridImp >::Parameters", "d4/d34/a01298.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::ParameterSpaceImpl< dim, dimworld, ScalarType >", "df/d2f/a01474.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::ParameterSpaceImpl< dim, dimworld, ScalarType >", "d0/d31/a01686.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridFamily< dim, dimworld, ScalarType >::ParameterSpaceTraits", "da/d36/a01482.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridFamily< dim, dimworld, ScalarType >::ParameterSpaceTraits", "d6/d01/a01690.html", null ],
    [ "Dune::IGA::GeometryKernel::PatchGeometryLocalView< codim, PatchGeometry, ParameterSpaceType_, LocalParameterSpaceGeometry >", "d6/d40/a01114.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridEntitySeed< codim, GridImp >", "d6/dc9/a01498.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridEntitySeed< codim, GridImp >", "d5/da6/a01698.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridFamily< dim, dimworld, ScalarType >", "d8/d7b/a01478.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridFamily< dim, dimworld, ScalarType >", "d5/d32/a01214.html", null ],
    [ "Dune::IGA::PatchGridFamily< dim, dimworld, ParameterSpaceType, ScalarType >", "d4/d22/a01250.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridHierarchicIterator< GridImp >", "de/d3c/a01490.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridHierarchicIterator< GridImp >", "de/d05/a01702.html", null ],
    [ "Dune::IGA::PatchGridLeafIntersection< GridImp >", "d3/d53/a01262.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridLeafIntersectionIterator< GridImp >", "d7/d90/a01530.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridLeafIntersectionIterator< GridImp >", "d8/dce/a01714.html", null ],
    [ "Dune::IGA::PatchGridLeafIntersectionIterator< GridImp >", "d6/d1e/a01234.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridLeafIterator< codim, pitype, GridImp >", "d1/d9b/a01566.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridLeafIterator< codim, pitype, GridImp >", "d5/d29/a01722.html", null ],
    [ "Dune::IGA::PatchGridLevelIntersection< GridImp >", "d7/d73/a01266.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridLevelIntersectionIterator< GridImp >", "dc/d2d/a01534.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridLevelIntersectionIterator< GridImp >", "db/d7f/a01718.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchGridLevelIterator< codim, pitype, GridImp >", "d5/d75/a01570.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchGridLevelIterator< codim, pitype, GridImp >", "df/dba/a01726.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::PatchTrimDataImpl< GridImp >", "d4/d49/a01590.html", null ],
    [ "Dune::IGA::IdentityParameterSpace::PatchTrimDataImpl< dim, ScalarType >", "dd/d08/a01682.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Preferences", "d3/d33/a01630.html", null ],
    [ "Dune::IGA::SimplexGenerator< GridImp >", "d7/d88/a01294.html", null ],
    [ "Dune::IGA::SimplexIntegrationRuleGenerator< GridImp >", "da/d79/a01310.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::VectorEntityContainer< GridImp >::StringAndIndex", "d1/de7/a01434.html", null ],
    [ "Dune::TensorProductCoordinates< ct, dim >", "d5/d17/a01098.html", null ],
    [ "Dune::Capabilities::threadSafe< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "da/dfb/a01174.html", null ],
    [ "Dune::Capabilities::threadSafe< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d3/dc7/a01170.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Transformations", "d1/d73/a01654.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedLeafIntersection< GridImp >", "da/dcf/a01558.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedLevelIntersection< GridImp >", "d2/dc1/a01562.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedLocalGeometryImpl< mydim, coorddim, GridImp, localGeometryTag >", "db/d7c/a01614.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedLocalGeometryImpl< 0, coorddim, GridImp, localGeometryTag >", "dd/d90/a01626.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedLocalGeometryImpl< 1, coorddim, GridImp, localGeometryTag >", "d1/d3a/a01622.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedLocalGeometryImpl< 2, coorddim, GridImp, localGeometryTag >", "d9/d6a/a01618.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedParameterSpaceGridEntity< codim_, dim, GridImp >", "d6/d51/a01494.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::TrimmedReferenceElement< dim, GridImp >", "d3/da5/a01598.html", null ],
    [ "std::true_type", null, [
      [ "is_instantiation_of< Template, Template< Args... > >", "dd/dec/a01782.html", null ]
    ] ],
    [ "Dune::Std::unexpected< E >", "d9/d37/a01754.html", null ],
    [ "UnstructuredDataCollectorInterface", null, [
      [ "Dune::Vtk::DiscontinuousIgaDataCollector< GridView >", "d8/dbe/a01370.html", null ]
    ] ],
    [ "Dune::IGA::DefaultParameterSpace::VectorEntityContainer< GridImp >", "d8/dd0/a01430.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::Util::ClippingResult::Vertex", "dd/d55/a01638.html", null ],
    [ "Dune::IGA::DefaultParameterSpace::ElementTrimDataImpl< Grid >::VertexInfo", "d1/df4/a01422.html", null ],
    [ "Dune::Capabilities::viewThreadSafe< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "dd/de9/a01182.html", null ],
    [ "Dune::Capabilities::viewThreadSafe< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d8/d11/a01178.html", null ],
    [ "Dune::YaspGrid< dim, Coordinates >", "d6/dea/a01094.html", null ],
    [ "Tree", null, [
      [ "iga.basis.Nurbs", "d5/dec/a01794.html", null ]
    ] ]
];