var hierarchy =
[
    [ "std::array< T >", null, [
      [ "Dune::IGA::Utilities::Domain< double >", "d6/d9a/a01083.html", null ],
      [ "Dune::IGA::Utilities::Domain< ScalarType >", "d6/d9a/a01083.html", null ]
    ] ],
    [ "BoundaryPatchEnclosingVerticesPropertyTrimmed< GridView, ncomp >", "de/d0f/a01727.html", null ],
    [ "Dune::IGA::Splines::BsplineBasis< ScalarType_ >", "de/dfe/a01383.html", null ],
    [ "Dune::Capabilities::canCommunicate< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "de/de4/a01135.html", null ],
    [ "Dune::Capabilities::canCommunicate< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d8/d84/a01131.html", null ],
    [ "Dune::IGA::DefaultTrim::Util::ClippingResult", "de/db6/a01627.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits::Codim< codim >", "d3/deb/a01619.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedReferenceElement< dim, GridImp >::Codim< codim >", "d5/d10/a01571.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits::Codim< codim >", "d6/d56/a01719.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedReferenceElement< dim, GridImp >::Codim< 0 >", "d5/d10/a01571.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< dim_, dimworld_, ScalarType >::ConnectionResult", "d6/dbc/a01099.html", null ],
    [ "Dune::IGA::ControlPoint< VT >", "d2/d4d/a01079.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchTrimDataImpl< GridImp >::CurveManager", "d8/d6c/a01563.html", null ],
    [ "DefaultLeafGridView", null, [
      [ "Dune::IGA::PatchGridLeafGridView< GridImp >", "de/dcb/a01263.html", null ]
    ] ],
    [ "DefaultLeafGridViewTraits", null, [
      [ "Dune::IGA::PatchGridLeafGridViewTraits< GridImp >", "dd/d39/a01271.html", null ]
    ] ],
    [ "DefaultLevelGridView", null, [
      [ "Dune::IGA::PatchGridLevelGridView< GridImp >", "dd/d42/a01259.html", null ]
    ] ],
    [ "DefaultLevelGridViewTraits", null, [
      [ "Dune::IGA::PatchGridLevelGridViewTraits< GridImp >", "d4/d41/a01267.html", null ]
    ] ],
    [ "Dune::DGFGridFactory< IGA::PatchGrid< dim, dimworld, GridFamily_, ScalarType > >", "d5/db3/a01751.html", null ],
    [ "Dune::DGFGridInfo< IGA::PatchGrid< dim, dimworld, GridFamily_, ScalarType > >", "d2/d7d/a01755.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, ScalarType >::DummyEmpty", "dd/d86/a01367.html", null ],
    [ "Dune::IGA::DefaultTrim::ElementTrimDataImpl< Grid >::EdgeInfo", "d8/d31/a01407.html", null ],
    [ "Dune::IGA::IdentityTrim::ElementTrimDataContainerImpl< ParameterSpaceGrid >", "df/d12/a01703.html", null ],
    [ "Dune::IGA::DefaultTrim::ElementTrimDataImpl< Grid >", "d6/d64/a01399.html", null ],
    [ "Dune::IGA::IdentityTrim::ElementTrimDataImpl< mydim_, ScalarType >", "d9/df7/a01699.html", null ],
    [ "Dune::IGA::DefaultTrim::ElementTrimDataImpl< GridImp >", "d6/d64/a01399.html", null ],
    [ "Dune::EnableBoundarySegmentIndexCheck< Grid >", "dc/d70/a01187.html", null ],
    [ "EnableLevelIntersectionIteratorCheck< Grid >", "d1/d0d/a01191.html", null ],
    [ "EnableLevelIntersectionIteratorCheck< Dune::IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d0/d5a/a01199.html", null ],
    [ "EntityDefaultImplementation", null, [
      [ "Dune::IGA::PatchGridEntity< codim, dim, GridImp >", "d7/ddd/a01223.html", null ],
      [ "Dune::IGA::PatchGridEntity< 0, dim, GridImp >", "d0/d88/a01231.html", null ]
    ] ],
    [ "Dune::IGA::DefaultTrim::EntityInfoImpl< Traits, codim >", "d9/ddc/a01423.html", null ],
    [ "Dune::IGA::DefaultTrim::EntityInfoImpl< Traits, 0 >", "d7/dfd/a01439.html", null ],
    [ "Dune::IGA::DefaultTrim::EntityInfoImpl< Traits, 1 >", "d7/d8b/a01431.html", null ],
    [ "Dune::IGA::DefaultTrim::EntityInfoImpl< Traits, 2 >", "db/d78/a01427.html", null ],
    [ "std::false_type", null, [
      [ "Dune::EnableBoundarySegmentIndexCheck< Dune::IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d8/df3/a01195.html", null ],
      [ "is_instantiation_of< Template, T >", "d5/d34/a01743.html", null ]
    ] ],
    [ "GeometryDefaultImplementation", null, [
      [ "Dune::IGA::PatchGridGeometry< mydim, coorddim, GridImp >", "d8/db0/a01243.html", null ],
      [ "Dune::IGA::PatchGridLocalGeometry< mydim, coorddim, GridImp >", "d0/d54/a01691.html", null ]
    ] ],
    [ "Dune::IGA::DefaultTrim::EntityInfoImpl< Traits, 1 >::GeometryMap", "d3/d95/a01435.html", null ],
    [ "GridDefaultImplementation", null, [
      [ "Dune::IGA::PatchGrid< dim, dimworld, GridFamily_, ScalarType >", "d5/d39/a01219.html", null ]
    ] ],
    [ "Dune::GridFactory< IGA::PatchGrid< dim_, dimworld_, TrimmerType_, ScalarType > >", "dd/dad/a01235.html", null ],
    [ "Dune::Capabilities::hasBackupRestoreFacilities< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d7/de8/a01159.html", null ],
    [ "Dune::Capabilities::hasBackupRestoreFacilities< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "db/d07/a01155.html", null ],
    [ "Dune::Capabilities::hasEntity< const Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "d0/d02/a01119.html", null ],
    [ "Dune::Capabilities::hasEntity< const IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d3/de1/a01111.html", null ],
    [ "Dune::Capabilities::hasEntity< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "df/dd5/a01115.html", null ],
    [ "Dune::Capabilities::hasEntityIterator< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "d9/d5b/a01127.html", null ],
    [ "Dune::Capabilities::hasEntityIterator< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "de/de5/a01123.html", null ],
    [ "std::hash< Dune::IGA::DefaultTrim::IdType< HostIdType > >", "d9/d13/a01599.html", null ],
    [ "Dune::IGA::DefaultTrim::HostGridAccess< Grid >", "d8/dd9/a01507.html", null ],
    [ "Dune::IGA::HostGridAccess< Grid >", "da/d3f/a01215.html", null ],
    [ "Dune::IGA::DefaultTrim::Util::ClippingResult::Vertex::HostVertexImpl", "dd/d2d/a01635.html", null ],
    [ "Dune::IGA::Ibra::IbraBase", "d9/de7/a01279.html", [
      [ "Dune::IGA::Ibra::IbraNURBSData< 1, 2 >", "d5/da7/a01283.html", null ],
      [ "Dune::IGA::Ibra::Brep< worldDim >", "d2/d4c/a01307.html", null ],
      [ "Dune::IGA::Ibra::BrepLoop", "d8/d38/a01299.html", null ],
      [ "Dune::IGA::Ibra::BrepLoopRepresentation", "d2/d68/a01295.html", null ],
      [ "Dune::IGA::Ibra::BrepRepresentation", "d6/d07/a01303.html", null ],
      [ "Dune::IGA::Ibra::BrepTrim", "d4/da0/a01291.html", null ],
      [ "Dune::IGA::Ibra::BrepTrimRepresentation", "d7/da4/a01287.html", null ],
      [ "Dune::IGA::Ibra::IbraNURBSData< dim, worldDim >", "d5/da7/a01283.html", null ]
    ] ],
    [ "Dune::IGA::IbraReader< dim, dimworld, PatchGrid, HasCurve >", "d1/d72/a01319.html", null ],
    [ "Dune::IGA::IbraReader< dim, dimworld, PatchGrid, false >", "d4/d2c/a01327.html", null ],
    [ "Dune::IGA::IbraReader< dim, dimworld, PatchGrid, true >", "db/da8/a01323.html", null ],
    [ "IdSet", null, [
      [ "Dune::IGA::DefaultTrim::PatchGridGlobalIdSet< GridImp >", "d6/d65/a01443.html", null ],
      [ "Dune::IGA::DefaultTrim::PatchGridLocalIdSet< GridImp >", "d2/dc4/a01483.html", null ],
      [ "Dune::IGA::IdentityTrim::PatchGridGlobalIdSet< GridImp >", "d5/de9/a01651.html", null ],
      [ "Dune::IGA::IdentityTrim::PatchGridLocalIdSet< GridImp >", "df/ddd/a01655.html", null ]
    ] ],
    [ "Dune::IGA::DefaultTrim::IdType< HostIdType >", "d0/d7d/a01419.html", null ],
    [ "Dune::IGA::IGARefinedGeometries< GridView >", "d4/d04/a01335.html", null ],
    [ "IndexSet", null, [
      [ "Dune::IGA::DefaultTrim::PatchGridLeafIndexSet< GridImp >", "da/d1e/a01479.html", null ],
      [ "Dune::IGA::DefaultTrim::PatchGridLevelIndexSet< GridImp >", "d7/d1d/a01475.html", null ],
      [ "Dune::IGA::IdentityTrim::PatchGridLeafIndexSet< GridImp >", "d4/d3c/a01671.html", null ],
      [ "Dune::IGA::IdentityTrim::PatchGridLevelIndexSet< GridImp >", "dd/d8d/a01667.html", null ]
    ] ],
    [ "Dune::IGA::DefaultTrim::Util::ClippingResult::Vertex::InsideVertexImpl", "d4/d49/a01643.html", null ],
    [ "Dune::Capabilities::isCartesian< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "dc/d2d/a01183.html", null ],
    [ "Dune::Capabilities::isCartesian< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "de/d1a/a01179.html", null ],
    [ "Dune::Capabilities::isLeafwiseConforming< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "de/df1/a01151.html", null ],
    [ "Dune::Capabilities::isLeafwiseConforming< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d8/ddb/a01147.html", null ],
    [ "Dune::Capabilities::isLevelwiseConforming< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "db/db2/a01143.html", null ],
    [ "Dune::Capabilities::isLevelwiseConforming< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d5/d3e/a01139.html", null ],
    [ "Dune::IteratorRange", null, [
      [ "Dune::IGA::DefaultTrim::TrimmedReferenceElement< dim, GridImp >::SubEntityRangeImpl", "d4/d2c/a01575.html", null ]
    ] ],
    [ "LeafBasisNode", null, [
      [ "Dune::Functions::NurbsNode< GV >", "dc/d4b/a01359.html", null ]
    ] ],
    [ "Dune::IGA::Trim::LocalGeometryVariant< TrimmerType_, Implementations >", "dc/de8/a01723.html", null ],
    [ "Dune::IGA::Splines::Nurbs< dim, ScalarType_ >::LocalView", "dc/dbc/a01391.html", null ],
    [ "Dune::IGA::MultiDimensionalNet< netdim, ElementType, Container >", "d6/d2e/a01735.html", null ],
    [ "Dune::IGA::MultiDimensionalNet< dim, ControlPointType >", "d6/d2e/a01735.html", null ],
    [ "Dune::IGA::MultiDimensionalNet< dim, ScalarType >", "d6/d2e/a01735.html", null ],
    [ "Dune::IGA::MultiDimensionalNetIndex< netdim >", "d1/d46/a01739.html", null ],
    [ "Dune::IGA::DefaultTrim::Util::ClippingResult::Vertex::NewVertexImpl", "db/dca/a01639.html", null ],
    [ "mapbox::util::nth< 0, Dune::FieldVector< T, 2 > >", "df/dc5/a01455.html", null ],
    [ "mapbox::util::nth< 1, Dune::FieldVector< T, 2 > >", "d6/d3b/a01459.html", null ],
    [ "Dune::IGA::Splines::Nurbs< dim, ScalarType_ >", "d9/d40/a01387.html", null ],
    [ "Dune::IGA::Splines::Nurbs< mydimension, ctype >", "d9/d40/a01387.html", null ],
    [ "Dune::IGA::Splines::Nurbs< mydimension, double >", "d9/d40/a01387.html", null ],
    [ "Dune::Functions::NurbsLocalBasis< GV, R >", "df/d96/a01347.html", null ],
    [ "Dune::Functions::NurbsLocalBasis< GV, double >", "df/d96/a01347.html", null ],
    [ "Dune::Functions::NurbsLocalCoefficients< dim >", "d1/dcd/a01351.html", null ],
    [ "Dune::Functions::NurbsLocalFiniteElement< GV, R >", "d3/da4/a01343.html", null ],
    [ "Dune::Functions::NurbsLocalFiniteElement< GV, double >", "d3/da4/a01343.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, LB >", "d8/d4e/a01355.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, Dune::Functions::NurbsLocalBasis< GV, double > >", "d8/d4e/a01355.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, Dune::Functions::NurbsLocalBasis< GV, R > >", "d8/d4e/a01355.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< dim_, dimworld_, ScalarType >", "de/d6d/a01095.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< dim, dimworld, ctype >", "de/d6d/a01095.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< GridImp::dimension, worlddimension, ctype >", "de/d6d/a01095.html", null ],
    [ "Dune::IGA::GeometryKernel::NURBSPatch< mydimension, coorddimension, ctype >", "de/d6d/a01095.html", null ],
    [ "Dune::IGA::NURBSPatchData< dim, dimworld_, ScalarType >", "d2/df5/a01395.html", null ],
    [ "Dune::IGA::NURBSPatchData< dim, dimworld >", "d2/df5/a01395.html", null ],
    [ "Dune::IGA::NURBSPatchData< dim, dimworld, ctype >", "d2/df5/a01395.html", null ],
    [ "Dune::IGA::NURBSPatchData< mydimension, worlddimension, ctype >", "d2/df5/a01395.html", null ],
    [ "Dune::IGA::NURBSPatchData< mydimension, worlddimension, double >", "d2/df5/a01395.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, ScalarType >", "da/d1f/a01203.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV >", "da/d1f/a01203.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, double >", "da/d1f/a01203.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, R >", "da/d1f/a01203.html", null ],
    [ "Dune::IGA::DefaultTrim::Parameter", "db/d51/a01603.html", null ],
    [ "Dune::IGA::IdentityTrim::Parameter", "dc/dc8/a01695.html", null ],
    [ "Dune::IGA::DefaultTrim::SimplexIntegrationRuleGenerator< GridImp >::Parameters", "d3/dbc/a01451.html", null ],
    [ "Dune::IGA::GeometryKernel::PatchGeometryLocalView< codim, PatchGeometry, TrimmerType_, LocalParameterSpaceGeometry >", "de/d4a/a01107.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridEntitySeed< codim, GridImp >", "d7/d42/a01463.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridEntitySeed< codim, GridImp >", "d4/dd4/a01659.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridFamily< dim, dimworld, ScalarType >", "d3/d79/a01611.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridFamily< dim, dimworld, ScalarType >", "d5/dad/a01207.html", null ],
    [ "Dune::IGA::PatchGridFamily< dim, dimworld, TrimmerType, ScalarType >", "d7/dbf/a01239.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridHierarchicIterator< GridImp >", "df/d5e/a01467.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridHierarchicIterator< GridImp >", "dd/d38/a01663.html", null ],
    [ "Dune::IGA::PatchGridLeafIntersection< GridImp >", "dc/dc2/a01251.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridLeafIntersectionIterator< GridImp >", "d5/d06/a01499.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridLeafIntersectionIterator< GridImp >", "db/d98/a01675.html", null ],
    [ "Dune::IGA::PatchGridLeafIntersectionIterator< GridImp >", "d9/da8/a01227.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridLeafIterator< codim, pitype, GridImp >", "dc/d93/a01535.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridLeafIterator< codim, pitype, GridImp >", "d2/dca/a01683.html", null ],
    [ "Dune::IGA::PatchGridLevelIntersection< GridImp >", "d7/d88/a01255.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridLevelIntersectionIterator< GridImp >", "d6/df5/a01503.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridLevelIntersectionIterator< GridImp >", "d2/d34/a01679.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridLevelIterator< codim, pitype, GridImp >", "d9/d80/a01539.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridLevelIterator< codim, pitype, GridImp >", "d7/db8/a01687.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchTrimDataImpl< GridImp >", "de/d1a/a01559.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchTrimDataImpl< dim, ScalarType >", "d0/d42/a01707.html", null ],
    [ "Preferences", "d2/dcc/a01623.html", null ],
    [ "Dune::IGA::DefaultTrim::SimplexIntegrationRuleGenerator< GridImp >", "df/d75/a01447.html", null ],
    [ "Dune::IGA::DefaultTrim::VectorEntityContainer< GridImp >::StringAndIndex", "de/d70/a01415.html", null ],
    [ "Dune::TensorProductCoordinates< ct, dim >", "d6/d0d/a01091.html", null ],
    [ "Dune::Capabilities::threadSafe< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d7/dd6/a01167.html", null ],
    [ "Dune::Capabilities::threadSafe< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d6/d27/a01163.html", null ],
    [ "Dune::IGA::DefaultTrim::Transformations", "d6/df0/a01647.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedLeafIntersection< GridImp >", "d8/d8c/a01527.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedLevelIntersection< GridImp >", "d4/d62/a01531.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedLocalGeometryImpl< mydim, coorddim, GridImp, localGeometryTag >", "d9/d1b/a01583.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedLocalGeometryImpl< 0, coorddim, GridImp, localGeometryTag >", "dc/dbf/a01595.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedLocalGeometryImpl< 1, coorddim, GridImp, localGeometryTag >", "dc/d42/a01591.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedLocalGeometryImpl< 2, coorddim, GridImp, localGeometryTag >", "d6/d91/a01587.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedParameterSpaceGridEntity< codim_, dim, GridImp >", "d5/d81/a01579.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmedReferenceElement< dim, GridImp >", "d7/d57/a01567.html", null ],
    [ "Dune::IGA::DefaultTrim::TrimmerImpl< dim, dimworld, ScalarType >", "d6/d82/a01607.html", null ],
    [ "Dune::IGA::IdentityTrim::TrimmerImpl< dim, dimworld, ScalarType >", "d8/df7/a01711.html", null ],
    [ "Dune::IGA::DefaultTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits", "d7/dae/a01615.html", null ],
    [ "Dune::IGA::IdentityTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits", "df/d9a/a01715.html", null ],
    [ "std::true_type", null, [
      [ "is_instantiation_of< Template, Template< Args... > >", "d7/db4/a01747.html", null ]
    ] ],
    [ "UnstructuredDataCollectorInterface", null, [
      [ "Dune::Vtk::DiscontinuousIgaDataCollector< GridView >", "dc/d8e/a01331.html", null ]
    ] ],
    [ "Dune::IGA::DefaultTrim::VectorEntityContainer< GridImp >", "db/d99/a01411.html", null ],
    [ "Dune::IGA::DefaultTrim::Util::ClippingResult::Vertex", "d0/da4/a01631.html", null ],
    [ "Dune::IGA::DefaultTrim::ElementTrimDataImpl< Grid >::VertexInfo", "da/d06/a01403.html", null ],
    [ "Dune::Capabilities::viewThreadSafe< Dune::Grid< dim, dimworld, ScalarType, IGA::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d6/df2/a01175.html", null ],
    [ "Dune::Capabilities::viewThreadSafe< IGA::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d2/d22/a01171.html", null ],
    [ "Dune::YaspGrid< dim, Coordinates >", "d0/d1f/a01087.html", null ],
    [ "Tree", null, [
      [ "iga.basis.Nurbs", "db/de5/a01759.html", null ]
    ] ]
];