var hierarchy =
[
    [ "std::array< T >", null, [
      [ "Dune::IGANEW::Utilities::Domain< double >", "dd/dee/a01081.html", null ],
      [ "Dune::IGANEW::Utilities::Domain< ScalarType >", "dd/dee/a01081.html", null ]
    ] ],
    [ "Dune::IGA::Boundary", "d4/d1a/a01405.html", null ],
    [ "BoundaryPatchEnclosingVerticesPropertyTrimmed< GridView, ncomp >", "d9/d8b/a01469.html", null ],
    [ "Dune::BoundarySegment", null, [
      [ "Dune::IGA::GridBoundarySegment< dim, Transformer >", "d4/dfd/a01465.html", null ]
    ] ],
    [ "Dune::IGANEW::Splines::BsplineBasis< ScalarType_ >", "de/d13/a01473.html", null ],
    [ "Dune::Capabilities::canCommunicate< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "db/d28/a01133.html", null ],
    [ "Dune::Capabilities::canCommunicate< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d9/d17/a01129.html", null ],
    [ "Dune::IGANEW::DefaultTrim::Util::ClippingResult", "df/d5a/a01681.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits::Codim< codim >", "d2/d44/a01677.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedReferenceElement< dim, GridImp >::Codim< codim >", "d7/d82/a01601.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits::Codim< codim >", "d5/d36/a01773.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedReferenceElement< dim, GridImp >::Codim< 0 >", "d7/d82/a01601.html", null ],
    [ "Dune::IGANEW::GeometryKernel::NURBSPatch< dim_, dimworld_, ScalarType >::ConnectionResult", "d1/dfa/a01097.html", null ],
    [ "Dune::IGANEW::ControlPoint< VT >", "d0/dd3/a01077.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchTrimDataImpl< GridImp >::CurveManager", "d9/dc8/a01593.html", null ],
    [ "DefaultLeafGridView", null, [
      [ "Dune::IGANEW::PatchGridLeafGridView< GridImp >", "d9/de7/a01257.html", null ]
    ] ],
    [ "DefaultLeafGridViewTraits", null, [
      [ "Dune::IGANEW::PatchGridLeafGridViewTraits< GridImp >", "da/dd8/a01265.html", null ]
    ] ],
    [ "DefaultLevelGridView", null, [
      [ "Dune::IGANEW::PatchGridLevelGridView< GridImp >", "d3/d0b/a01253.html", null ]
    ] ],
    [ "DefaultLevelGridViewTraits", null, [
      [ "Dune::IGANEW::PatchGridLevelGridViewTraits< GridImp >", "de/d34/a01261.html", null ]
    ] ],
    [ "Dune::DGFGridFactory< Dune::IGA::NURBSGrid< gridDim, worldDim, ScalarType > >", "d0/d95/a01389.html", null ],
    [ "Dune::DGFGridInfo< Dune::IGA::NURBSGrid< gridDim, worldDim, ScalarType > >", "da/d77/a01381.html", null ],
    [ "Dune::IGA::DomainInformation", "dc/d60/a01461.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, ScalarType >::DummyEmpty", "df/d29/a01329.html", null ],
    [ "Dune::IGANEW::DefaultTrim::ElementTrimDataImpl< Grid >::EdgeInfo", "db/d1e/a01497.html", null ],
    [ "Dune::IGA::Trim::ElementBoundaries", "d7/d68/a01413.html", null ],
    [ "Dune::IGANEW::IdentityTrim::ElementTrimDataContainerImpl< ParameterSpaceGrid >", "db/dc0/a01757.html", null ],
    [ "Dune::IGANEW::DefaultTrim::ElementTrimDataImpl< Grid >", "d2/dac/a01489.html", null ],
    [ "Dune::IGANEW::IdentityTrim::ElementTrimDataImpl< mydim_, ScalarType >", "d6/d72/a01753.html", null ],
    [ "Dune::IGANEW::DefaultTrim::ElementTrimDataImpl< GridImp >", "d2/dac/a01489.html", null ],
    [ "Dune::EnableBoundarySegmentIndexCheck< Grid >", "d3/dd3/a01185.html", null ],
    [ "EnableLevelIntersectionIteratorCheck< Grid >", "d3/d10/a01189.html", null ],
    [ "EnableLevelIntersectionIteratorCheck< Dune::IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d4/d10/a01197.html", null ],
    [ "EntityDefaultImplementation", null, [
      [ "Dune::IGANEW::PatchGridEntity< codim, dim, GridImp >", "dd/d3f/a01221.html", null ],
      [ "Dune::IGANEW::PatchGridEntity< 0, dim, GridImp >", "db/d1c/a01229.html", null ]
    ] ],
    [ "Dune::IGANEW::DefaultTrim::EntityInfoImpl< Traits, codim >", "d0/d90/a01641.html", null ],
    [ "Dune::IGANEW::DefaultTrim::EntityInfoImpl< Traits, 0 >", "d3/d21/a01657.html", null ],
    [ "Dune::IGANEW::DefaultTrim::EntityInfoImpl< Traits, 1 >", "dc/d87/a01649.html", null ],
    [ "Dune::IGANEW::DefaultTrim::EntityInfoImpl< Traits, 2 >", "d7/d53/a01645.html", null ],
    [ "std::false_type", null, [
      [ "Dune::EnableBoundarySegmentIndexCheck< Dune::IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "dd/d43/a01193.html", null ],
      [ "is_instantiation_of< Template, T >", "d4/dc6/a01793.html", null ]
    ] ],
    [ "GeometryDefaultImplementation", null, [
      [ "Dune::IGANEW::PatchGridGeometry< mydim, coorddim, GridImp >", "d3/d07/a01241.html", null ],
      [ "Dune::IGANEW::PatchGridLocalGeometry< mydim, coorddim, GridImp >", "d0/d78/a01745.html", null ]
    ] ],
    [ "Dune::IGANEW::DefaultTrim::EntityInfoImpl< Traits, 1 >::GeometryMap", "d1/d03/a01653.html", null ],
    [ "GridDefaultImplementation", null, [
      [ "Dune::IGANEW::PatchGrid< dim, dimworld, GridFamily_, ScalarType >", "da/d19/a01217.html", null ]
    ] ],
    [ "Dune::GridFactory< IGANEW::PatchGrid< dim_, dimworld_, TrimmerType_, ScalarType > >", "d6/da1/a01233.html", null ],
    [ "Dune::Capabilities::hasBackupRestoreFacilities< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d9/d25/a01157.html", null ],
    [ "Dune::Capabilities::hasBackupRestoreFacilities< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "dc/d06/a01153.html", null ],
    [ "Dune::Capabilities::hasEntity< const Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "d6/d8b/a01117.html", null ],
    [ "Dune::Capabilities::hasEntity< const IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d8/dbf/a01109.html", null ],
    [ "Dune::Capabilities::hasEntity< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "d8/ded/a01113.html", null ],
    [ "Dune::Capabilities::hasEntityIterator< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > >, codim >", "d6/dc4/a01125.html", null ],
    [ "Dune::Capabilities::hasEntityIterator< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType >, codim >", "dd/de4/a01121.html", null ],
    [ "std::hash< Dune::IGANEW::DefaultTrim::IdType< HostIdType > >", "db/d95/a01637.html", null ],
    [ "Dune::IGANEW::DefaultTrim::HostGridAccess< Grid >", "de/d2c/a01553.html", null ],
    [ "Dune::IGANEW::HostGridAccess< Grid >", "d5/d54/a01213.html", null ],
    [ "Dune::IGANEW::DefaultTrim::Util::ClippingResult::Vertex::HostVertexImpl", "da/d20/a01689.html", null ],
    [ "Dune::IGA::Ibra::IbraBase", "de/da0/a01341.html", [
      [ "Dune::IGA::Ibra::IbraNURBSData< 1, 2 >", "d4/deb/a01345.html", null ],
      [ "Dune::IGA::Ibra::Brep< worldDim >", "d1/d17/a01369.html", null ],
      [ "Dune::IGA::Ibra::BrepLoop", "d2/d1f/a01361.html", null ],
      [ "Dune::IGA::Ibra::BrepLoopRepresentation", "df/d10/a01357.html", null ],
      [ "Dune::IGA::Ibra::BrepRepresentation", "d7/d81/a01365.html", null ],
      [ "Dune::IGA::Ibra::BrepTrim", "d4/dad/a01353.html", null ],
      [ "Dune::IGA::Ibra::BrepTrimRepresentation", "de/d6c/a01349.html", null ],
      [ "Dune::IGA::Ibra::IbraNURBSData< dim, worldDim >", "d4/deb/a01345.html", null ]
    ] ],
    [ "Dune::IGANEW::Ibra::IbraBase", "d6/d16/a01269.html", [
      [ "Dune::IGANEW::Ibra::Brep< worldDim >", "dc/d8c/a01297.html", null ],
      [ "Dune::IGANEW::Ibra::BrepLoop", "d9/dda/a01289.html", null ],
      [ "Dune::IGANEW::Ibra::BrepLoopRepresentation", "d1/d1a/a01285.html", null ],
      [ "Dune::IGANEW::Ibra::BrepRepresentation", "dc/dd5/a01293.html", null ],
      [ "Dune::IGANEW::Ibra::BrepTrim", "d5/d6f/a01281.html", null ],
      [ "Dune::IGANEW::Ibra::BrepTrimRepresentation", "d2/d1d/a01277.html", null ],
      [ "Dune::IGANEW::Ibra::IbraNURBSData< dim, worldDim >", "de/d85/a01273.html", null ]
    ] ],
    [ "Dune::IGA::IbraReader< gridDim, worldDim, ScalarType >", "d3/dea/a01377.html", null ],
    [ "Dune::IGANEW::IbraReader< dim, dimworld, PatchGrid >", "d3/d07/a01301.html", null ],
    [ "IdSet", null, [
      [ "Dune::IGANEW::DefaultTrim::PatchGridGlobalIdSet< GridImp >", "db/d06/a01509.html", null ],
      [ "Dune::IGANEW::DefaultTrim::PatchGridLocalIdSet< GridImp >", "db/dce/a01529.html", null ],
      [ "Dune::IGANEW::IdentityTrim::PatchGridGlobalIdSet< GridImp >", "db/d66/a01721.html", null ],
      [ "Dune::IGANEW::IdentityTrim::PatchGridLocalIdSet< GridImp >", "d3/d5e/a01725.html", null ]
    ] ],
    [ "Dune::IGANEW::DefaultTrim::IdType< HostIdType >", "d6/dd6/a01633.html", null ],
    [ "Dune::IGA::IGARefinedGeometries< GridView >", "d3/d92/a01393.html", null ],
    [ "IndexSet", null, [
      [ "Dune::IGANEW::DefaultTrim::PatchGridLeafIndexSet< GridImp >", "db/de9/a01525.html", null ],
      [ "Dune::IGANEW::DefaultTrim::PatchGridLevelIndexSet< GridImp >", "dc/d42/a01521.html", null ],
      [ "Dune::IGANEW::IdentityTrim::PatchGridLeafIndexSet< GridImp >", "dd/ddb/a01717.html", null ],
      [ "Dune::IGANEW::IdentityTrim::PatchGridLevelIndexSet< GridImp >", "d2/d0c/a01713.html", null ]
    ] ],
    [ "Dune::IGANEW::DefaultTrim::Util::ClippingResult::Vertex::InsideVertexImpl", "d6/d15/a01697.html", null ],
    [ "Dune::Capabilities::isCartesian< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "de/db5/a01181.html", null ],
    [ "Dune::Capabilities::isCartesian< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "dc/d98/a01177.html", null ],
    [ "Dune::Capabilities::isLeafwiseConforming< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d8/d02/a01149.html", null ],
    [ "Dune::Capabilities::isLeafwiseConforming< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d9/d65/a01145.html", null ],
    [ "Dune::Capabilities::isLevelwiseConforming< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "de/df6/a01141.html", null ],
    [ "Dune::Capabilities::isLevelwiseConforming< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d6/d6e/a01137.html", null ],
    [ "Dune::IteratorRange", null, [
      [ "Dune::IGANEW::DefaultTrim::TrimmedReferenceElement< dim, GridImp >::SubEntityRangeImpl", "d5/d75/a01605.html", null ]
    ] ],
    [ "Dune::JSONGridFactory< Grid_ >", "df/d68/a01385.html", null ],
    [ "LeafBasisNode", null, [
      [ "Dune::Functions::NurbsNode< GV >", "d9/d5c/a01321.html", null ],
      [ "Dune::Functions::NurbsNode< GV >", "d9/d5c/a01321.html", null ]
    ] ],
    [ "Dune::IGANEW::Trim::LocalGeometryVariant< TrimmerType_, Implementations >", "d3/dac/a01777.html", null ],
    [ "Dune::IGANEW::Splines::Nurbs< dim, ScalarType_ >::LocalView", "d1/de4/a01481.html", null ],
    [ "Dune::IGANEW::MultiDimensionalNet< netdim, ElementType, Container >", "d7/d10/a01785.html", null ],
    [ "Dune::IGANEW::MultiDimensionalNet< dim, ControlPointType >", "d7/d10/a01785.html", null ],
    [ "Dune::IGANEW::MultiDimensionalNet< dim, ScalarType >", "d7/d10/a01785.html", null ],
    [ "Dune::IGANEW::MultiDimensionalNetIndex< netdim >", "d6/d53/a01789.html", null ],
    [ "Dune::IGANEW::DefaultTrim::Util::ClippingResult::Vertex::NewVertexImpl", "dd/db4/a01693.html", null ],
    [ "Dune::IGANEW::Splines::Nurbs< dim, ScalarType_ >", "d8/d67/a01477.html", null ],
    [ "Dune::IGANEW::Splines::Nurbs< mydimension, ctype >", "d8/d67/a01477.html", null ],
    [ "Dune::IGANEW::Splines::Nurbs< mydimension, double >", "d8/d67/a01477.html", null ],
    [ "Dune::IGA::NURBSGrid< dim, dimworld, ScalarType >", "d7/d38/a01373.html", null ],
    [ "Dune::Functions::NurbsLocalBasis< GV, R >", "db/d4b/a01309.html", null ],
    [ "Dune::Functions::NurbsLocalBasis< GV, double >", "db/d4b/a01309.html", null ],
    [ "Dune::Functions::NurbsLocalCoefficients< dim >", "de/d90/a01313.html", null ],
    [ "Dune::Functions::NurbsLocalFiniteElement< GV, R >", "dc/d9e/a01305.html", null ],
    [ "Dune::Functions::NurbsLocalFiniteElement< GV, double >", "dc/d9e/a01305.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, LB >", "df/db8/a01317.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, Dune::Functions::NurbsLocalBasis< GV, double > >", "df/db8/a01317.html", null ],
    [ "Dune::Functions::NurbsLocalInterpolation< dim, Dune::Functions::NurbsLocalBasis< GV, R > >", "df/db8/a01317.html", null ],
    [ "Dune::IGANEW::GeometryKernel::NURBSPatch< dim_, dimworld_, ScalarType >", "de/d1c/a01093.html", null ],
    [ "Dune::IGANEW::GeometryKernel::NURBSPatch< dim, dimworld, ctype >", "de/d1c/a01093.html", null ],
    [ "Dune::IGANEW::GeometryKernel::NURBSPatch< GridImp::dimension, worlddimension, ctype >", "de/d1c/a01093.html", null ],
    [ "Dune::IGANEW::GeometryKernel::NURBSPatch< mydim, dim, ctype >", "de/d1c/a01093.html", null ],
    [ "Dune::IGANEW::GeometryKernel::NURBSPatch< mydimension, coorddimension, ctype >", "de/d1c/a01093.html", null ],
    [ "Dune::IGANEW::NURBSPatchData< dim, dimworld_, ScalarType >", "d4/d39/a01485.html", null ],
    [ "Dune::IGANEW::NURBSPatchData< dim - 1, dim, ctype >", "d4/d39/a01485.html", null ],
    [ "Dune::IGANEW::NURBSPatchData< dim, dimworld >", "d4/d39/a01485.html", null ],
    [ "Dune::IGANEW::NURBSPatchData< dim, dimworld, ctype >", "d4/d39/a01485.html", null ],
    [ "Dune::IGANEW::NURBSPatchData< mydimension, worlddimension, ctype >", "d4/d39/a01485.html", null ],
    [ "Dune::IGANEW::NURBSPatchData< mydimension, worlddimension, double >", "d4/d39/a01485.html", null ],
    [ "Dune::IGA::Trim::NURBSPatchTrimmer< intType_, sc_ >", "de/daf/a01417.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, ScalarType >", "de/df7/a01201.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV >", "de/df7/a01201.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, double >", "de/df7/a01201.html", null ],
    [ "Dune::Functions::NurbsPreBasis< GV, R >", "de/df7/a01201.html", null ],
    [ "Dune::IGANEW::DefaultTrim::Parameter", "d4/d41/a01661.html", null ],
    [ "Dune::IGANEW::IdentityTrim::Parameter", "d5/d77/a01749.html", null ],
    [ "Dune::IGANEW::GeometryKernel::PatchGeometryLocalView< codim, PatchGeometry, TrimmerType_, LocalParameterSpaceGeometry >", "de/d1d/a01105.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridEntitySeed< codim, GridImp >", "d0/d62/a01513.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridEntitySeed< codim, GridImp >", "d9/dc5/a01705.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridFamily< dim, dimworld, ScalarType >", "dc/dec/a01669.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridFamily< dim, dimworld, ScalarType >", "de/d61/a01205.html", null ],
    [ "Dune::IGANEW::PatchGridFamily< dim, dimworld, TrimmerType, ScalarType >", "dc/dab/a01237.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridHierarchicIterator< GridImp >", "dc/d96/a01517.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridHierarchicIterator< GridImp >", "d1/da7/a01709.html", null ],
    [ "Dune::IGANEW::PatchGridLeafIntersection< GridImp >", "d1/d31/a01245.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridLeafIntersectionIterator< GridImp >", "dd/dba/a01545.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridLeafIntersectionIterator< GridImp >", "d2/d70/a01729.html", null ],
    [ "Dune::IGANEW::PatchGridLeafIntersectionIterator< GridImp >", "d8/d53/a01225.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridLeafIterator< codim, pitype, GridImp >", "d6/d82/a01565.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridLeafIterator< codim, pitype, GridImp >", "df/d2e/a01737.html", null ],
    [ "Dune::IGANEW::PatchGridLevelIntersection< GridImp >", "d3/d7b/a01249.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridLevelIntersectionIterator< GridImp >", "d3/d1b/a01549.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridLevelIntersectionIterator< GridImp >", "d8/d9c/a01733.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridLevelIterator< codim, pitype, GridImp >", "d9/d32/a01569.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridLevelIterator< codim, pitype, GridImp >", "d0/d4e/a01741.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchTrimDataImpl< GridImp >", "d7/d29/a01589.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchTrimDataImpl< dim, ScalarType >", "db/db8/a01761.html", null ],
    [ "Dune::IGANEW::DefaultTrim::VectorEntityContainer< GridImp >::StringAndIndex", "dc/dce/a01505.html", null ],
    [ "Dune::TensorProductCoordinates< ct, dim >", "d3/dc4/a01089.html", null ],
    [ "Dune::Capabilities::threadSafe< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d8/d92/a01165.html", null ],
    [ "Dune::Capabilities::threadSafe< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "dc/d81/a01161.html", null ],
    [ "Dune::IGANEW::DefaultTrim::Transformations", "d1/db5/a01701.html", null ],
    [ "Dune::IGA::TransformToSpan< dim >", "da/df7/a01457.html", null ],
    [ "Dune::IGA::TrimData", "d9/d6e/a01409.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedLeafIntersection< GridImp >", "d9/dac/a01557.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedLevelIntersection< GridImp >", "d2/d49/a01561.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedLocalGeometryImpl< mydim, coorddim, GridImp, localGeometryTag >", "d6/d6d/a01617.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedLocalGeometryImpl< 0, coorddim, GridImp, localGeometryTag >", "dc/d62/a01629.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedLocalGeometryImpl< 1, coorddim, GridImp, localGeometryTag >", "d3/d2d/a01625.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedLocalGeometryImpl< 2, coorddim, GridImp, localGeometryTag >", "dd/dda/a01621.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedParameterSpaceGridEntity< codim_, dim, GridImp >", "da/d24/a01609.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmedReferenceElement< dim, GridImp >", "d0/d1d/a01597.html", null ],
    [ "Dune::IGANEW::DefaultTrim::TrimmerImpl< dim, dimworld, ScalarType >", "d9/d45/a01665.html", null ],
    [ "Dune::IGANEW::IdentityTrim::TrimmerImpl< dim, dimworld, ScalarType >", "df/d7b/a01765.html", null ],
    [ "Dune::IGANEW::DefaultTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits", "d9/df5/a01673.html", null ],
    [ "Dune::IGANEW::IdentityTrim::PatchGridFamily< dim, dimworld, ScalarType >::TrimmerTraits", "d7/d6d/a01769.html", null ],
    [ "std::true_type", null, [
      [ "is_instantiation_of< Template, Template< Args... > >", "d4/dd1/a01797.html", null ]
    ] ],
    [ "Dune::IGANEW::DefaultTrim::VectorEntityContainer< GridImp >", "db/d2c/a01501.html", null ],
    [ "Dune::IGANEW::DefaultTrim::Util::ClippingResult::Vertex", "de/d96/a01685.html", null ],
    [ "Dune::IGANEW::DefaultTrim::ElementTrimDataImpl< Grid >::VertexInfo", "d2/d41/a01493.html", null ],
    [ "Dune::Capabilities::viewThreadSafe< Dune::Grid< dim, dimworld, ScalarType, IGANEW::PatchGridFamily< dim, dimworld, GridFamilyTraits, ScalarType > > >", "d7/d0c/a01173.html", null ],
    [ "Dune::Capabilities::viewThreadSafe< IGANEW::PatchGrid< dim, dimworld, GridFamilyTraits, ScalarType > >", "d7/daf/a01169.html", null ],
    [ "Dune::YaspGrid< dim, Coordinates >", "d2/df3/a01085.html", null ],
    [ "Tree", null, [
      [ "iga.basis.Nurbs", "d2/d42/a01801.html", null ]
    ] ]
];